CREATE TABLE geo_county as select fromtable.source,fromtable.id,electoral_district_long0.id as electoral_district_id
from geo_county_long as fromtable left join electoral_district_long as electoral_district_long0 on fromtable.electoral_district_id_long = electoral_district_long0.id_long;
CREATE TABLE electoral_district as select fromtable.name,fromtable.number,fromtable.source,fromtable.type,fromtable.id,state_long0.id as state_id
from electoral_district_long as fromtable left join state_long as state_long0 on fromtable.state_id_long = state_long0.id_long;
CREATE TABLE geo_cd as select fromtable.source,fromtable.id,electoral_district_long0.id as electoral_district_id
from geo_cd_long as fromtable left join electoral_district_long as electoral_district_long0 on fromtable.electoral_district_id_long = electoral_district_long0.id_long;
CREATE TABLE election_administration as select fromtable.rules_url,fromtable.id,fromtable.am_i_registered_url,fromtable.source,fromtable.type,fromtable.elections_url,fromtable.absentee_url,fromtable.hours,fromtable.where_do_i_vote_url,fromtable.voter_services,fromtable.name,fromtable.registration_url,fromtable.what_is_on_my_ballot_url,state_long0.id as state_id,geo_address_long1.id as physical_address,election_official_long2.id as ovc_id,election_official_long3.id as eo_id,geo_address_long4.id as mailing_address
from election_administration_long as fromtable left join state_long as state_long0 on fromtable.state_id_long = state_long0.id_long left join geo_address_long as geo_address_long1 on fromtable.physical_address_long = geo_address_long1.id_long left join election_official_long as election_official_long2 on fromtable.ovc_id_long = election_official_long2.id_long left join election_official_long as election_official_long3 on fromtable.eo_id_long = election_official_long3.id_long left join geo_address_long as geo_address_long4 on fromtable.mailing_address_long = geo_address_long4.id_long;
CREATE TABLE polling_location as select fromtable.source,fromtable.polling_hours,fromtable.directions,fromtable.id,fromtable.photo_url,geo_address_long0.id as address
from polling_location_long as fromtable left join geo_address_long as geo_address_long0 on fromtable.address_long = geo_address_long0.id_long;
CREATE TABLE election as select fromtable.registration_deadline,fromtable.statewide,fromtable.absentee_ballot_info,fromtable.registration_info,fromtable.election_type,fromtable.source,fromtable.absentee_request_deadline,fromtable.polling_hours,fromtable.results_url,fromtable.date,fromtable.election_day_registration,fromtable.id,state_long0.id as state_id
from election_long as fromtable left join state_long as state_long0 on fromtable.state_id_long = state_long0.id_long;
CREATE TABLE candidate_in_contest as select fromtable.sort_order,contest_long0.id as contest_id,candidate_long1.id as candidate_id
from candidate_in_contest_long as fromtable left join contest_long as contest_long0 on fromtable.contest_id_long = contest_long0.id_long left join candidate_long as candidate_long1 on fromtable.candidate_id_long = candidate_long1.id_long;
CREATE TABLE geo_address as select fromtable.street_name,fromtable.line1,fromtable.house_number_prefix,fromtable.id,fromtable.zip4,fromtable.is_geocoded,fromtable.is_standardized,fromtable.apartment,fromtable.location_name,fromtable.ycoord,fromtable.house_number,fromtable.line3,fromtable.line2,fromtable.street_suffix,fromtable.source,fromtable.state,fromtable.city,fromtable.xcoord,fromtable.address_direction,fromtable.house_number_suffix,fromtable.zip,fromtable.street_direction
from geo_address_long as fromtable;
CREATE TABLE candidate as select fromtable.name,fromtable.phone,fromtable.facebook_url,fromtable.email,fromtable.candidate_url,fromtable.source,fromtable.google_plus_url,fromtable.twitter_name,fromtable.incumbent,fromtable.party,fromtable.wiki_word,fromtable.id,fromtable.biography,fromtable.photo_url,geo_address_long0.id as filed_mailing_address
from candidate_long as fromtable left join geo_address_long as geo_address_long0 on fromtable.filed_mailing_address_long = geo_address_long0.id_long;
CREATE TABLE contest as select fromtable.number_voting_for,fromtable.office,fromtable.filing_closed_date,fromtable.type,fromtable.partisan,fromtable.number_elected,fromtable.custom_ballot_heading,fromtable.contest_type,fromtable.electorate_specifications,fromtable.write_in,fromtable.source,fromtable.ballot_placement,fromtable.primary_party,fromtable.id,fromtable.special,electoral_district_long0.id as electoral_district_id,election_long1.id as election_id
from contest_long as fromtable left join electoral_district_long as electoral_district_long0 on fromtable.electoral_district_id_long = electoral_district_long0.id_long left join election_long as election_long1 on fromtable.election_id_long = election_long1.id_long;
CREATE TABLE referendum as select fromtable.subtitle,fromtable.title,fromtable.text,fromtable.con_statement,fromtable.effect_of_abstain,fromtable.brief,fromtable.source,fromtable.passage_threshold,fromtable.id,fromtable.pro_statement,contest_long0.id as contest_id
from referendum_long as fromtable left join contest_long as contest_long0 on fromtable.contest_id_long = contest_long0.id_long;
CREATE TABLE source as select fromtable.user_id,fromtable.name,fromtable.acquired,fromtable.source_data_file_url,fromtable.reviewing_user_id,fromtable.reviewed,fromtable.source,fromtable.hash,fromtable.organization_url,fromtable.id,fromtable.description
from source_long as fromtable;
CREATE TABLE state as select fromtable.source,fromtable.postal_code,fromtable.id,fromtable.name
from state_long as fromtable;
CREATE TABLE precinct__polling_location as select polling_location_long0.id as polling_location_id,precinct_long1.id as precinct_id
from precinct__polling_location_long as fromtable left join polling_location_long as polling_location_long0 on fromtable.polling_location_id_long = polling_location_long0.id_long left join precinct_long as precinct_long1 on fromtable.precinct_id_long = precinct_long1.id_long;
CREATE TABLE precinct as select fromtable.ballot_style_image_url,fromtable.electoral_district_id,fromtable.early_vote_site_id,fromtable.name,fromtable.number,fromtable.source,fromtable.locality_id,fromtable.mail_only,fromtable.is_split,fromtable.ward,fromtable.id,election_administration_long0.id as election_administration_id,state_long1.id as state_id,precinct_long2.id as parent_id,fromtable.polling_location_id_long as polling_location_id
from precinct_long as fromtable left join election_administration_long as election_administration_long0 on fromtable.election_administration_id_long = election_administration_long0.id_long left join state_long as state_long1 on fromtable.state_id_long = state_long1.id_long left join precinct_long as precinct_long2 on fromtable.parent_id_long = precinct_long2.id_long;
CREATE TABLE electoral_district__precinct as select precinct_long0.id as precinct_id,electoral_district_long1.id as electoral_district_id
from electoral_district__precinct_long as fromtable left join precinct_long as precinct_long0 on fromtable.precinct_id_long = precinct_long0.id_long left join electoral_district_long as electoral_district_long1 on fromtable.electoral_district_id_long = electoral_district_long1.id_long;
CREATE TABLE precinct__early_vote_site as select precinct_long0.id as precinct_id,early_vote_site_long1.id as early_vote_site_id
from precinct__early_vote_site_long as fromtable left join precinct_long as precinct_long0 on fromtable.precinct_id_long = precinct_long0.id_long left join early_vote_site_long as early_vote_site_long1 on fromtable.early_vote_site_id_long = early_vote_site_long1.id_long;
CREATE TABLE geo_ss as select fromtable.source,fromtable.id,electoral_district_long0.id as electoral_district_id
from geo_ss_long as fromtable left join electoral_district_long as electoral_district_long0 on fromtable.electoral_district_id_long = electoral_district_long0.id_long;
CREATE TABLE geo_sh as select fromtable.source,fromtable.id,electoral_district_long0.id as electoral_district_id
from geo_sh_long as fromtable left join electoral_district_long as electoral_district_long0 on fromtable.electoral_district_id_long = electoral_district_long0.id_long;
CREATE TABLE ballot_response as select fromtable.text,fromtable.source,fromtable.sort_order,fromtable.id,contest_long0.id as contest_id
from ballot_response_long as fromtable left join contest_long as contest_long0 on fromtable.contest_id_long = contest_long0.id_long;
CREATE TABLE early_vote_site as select fromtable.name,fromtable.end_date,fromtable.start_date,fromtable.source,fromtable.voter_services,fromtable.directions,fromtable.days_time_open,fromtable.id,state_long0.id as state_id,geo_address_long1.id as address
from early_vote_site_long as fromtable left join state_long as state_long0 on fromtable.state_id_long = state_long0.id_long left join geo_address_long as geo_address_long1 on fromtable.address_long = geo_address_long1.id_long;
CREATE TABLE street_segment as select fromtable.start_house_number,fromtable.source,fromtable.end_house_number,fromtable.odd_even_both,fromtable.end_apartment_number,fromtable.id,fromtable.start_apartment_number,geo_address_long0.id as non_house_address,precinct_long1.id as precinct_id,precinct_long2.id as precinct_split_id
from street_segment_long as fromtable left join geo_address_long as geo_address_long0 on fromtable.non_house_address_long = geo_address_long0.id_long left join precinct_long as precinct_long1 on fromtable.precinct_id_long = precinct_long1.id_long left join precinct_long as precinct_long2 on fromtable.precinct_split_id_long = precinct_long2.id_long;
CREATE TABLE election_official as select fromtable.fax,fromtable.name,fromtable.phone,fromtable.title,fromtable.id,fromtable.source,fromtable.email
from election_official_long as fromtable;
CREATE TABLE org_custom_field as select fromtable.source_pk,fromtable.parent_id,fromtable.type,fromtable.org_id,fromtable.value
from org_custom_field_long as fromtable;
