CREATE table voter_file (
id int4 DEFAULT nextval('pksq'),
sos_voterid varchar(50),
county_number varchar(20),
county_id varchar(50),
residential_address1 varchar(255),
residential_secondary_addr varchar(255),
residential_city varchar(255),
residential_state varchar(10),
residential_zip varchar(10),
residential_zip_plus4 varchar(4),
residential_country varchar(50),
residential_postalcode varchar(50),
mailing_address1 varchar(255),
mailing_secondary_address varchar(255),
mailing_city varchar(255),
mailing_state varchar(10),
mailing_zip varchar(10),
mailing_zip_plus4 varchar(4),
mailing_country varchar(50),
mailing_postal_code varchar(50),
judicial_district varchar(255),
congressional_district varchar(255),
city_council varchar(255),
county_council varchar(255),
municipal_district varchar(255),
school_district varchar(255),
state_representative_district varchar(255),
state_senate_district varchar(255),
precinct_name varchar(255),
precinct_code varchar(255),
township varchar(255),
ward varchar(255),
source varchar(255),
election varchar(255),
election_key int4--,
--PRIMARY KEY (id),
--UNIQUE (sos_voterid)
);
